### ISSUE TITLE
VIEW Cannot find IEditBox interface.

### ISSUE THREAD

**Issue by TheColonel2688** [Dirkster99/InplaceEditBoxLib#1]
I have placed this in a TreeView and it seems to be working just fine except in the output window I receive this for every EditBox that is loaded.

> VIEW Cannot find IEditBox interface.

```
 <views1:EditBox Text="{Binding Path=Name, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}"
                                        DisplayText="{Binding Path=Name, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}" 
                                        RenameCommand="{Binding Path=Data.Step_Rename, Source={StaticResource proxy}}"
                                        RenameCommandParameter="{Binding}"
                                        Focusable="True"
                                        VerticalAlignment="Stretch"
                                        HorizontalAlignment="Left"
                                        />
```

**Comment by TheColonel2688** [comment]
So just to clarify, each item that you want to be able to edit in place needs to have it's own view Model?

So if I have a VM with string FirstName, string LastName, and string MiddleName, each one of those need to be wrapped in its own child view model that implements IEditBox?

**Comment by Dirkster99** [comment]
Thats a Yes - otherwise, if you do not need editing capabilities you could just use a textblock instead.

You could use a viewmodel base class like in the demo and simply change that data source of each instance, or have a generic version of it, and instantiate a more specific version for each item that you want to be editable in a collection:
https://github.com/Dirkster99/InplaceEditBoxLib/blob/master/source/InplaceEditBoxLib/ViewModels/EditInPlaceViewModel.cs

Editing more than one item in a collection is new to me since I've used this in the tree view only - but the technical implementation is such that I don't see problems for usage in other (list) controls. That is, I cannot give you a sample implementation but you should be able to work it out from the tree view based sample - otherwise, please share a sample and we can see what we see there ...

**Comment by TheColonel2688** [comment]
Thank you Dirkster99. I much appreciate the explanation.
