### ISSUE TITLE
EditBox not working in ListView

### ISSUE THREAD

**Issue by LokiMidgard** [Dirkster99/InplaceEditBoxLib#12]
I have tried to use the Editbox but it does not work in ListViews. In TreeViews it seems to have no problems.

I created a [minimal sample](LokiMidgard/BUG-InlineEditBox-ListView-Not-Working).

The problem seems to be that if I start the editing it will directly be canceled.
Going into edit mode triggesr `OnScrollViewerChanged` in a ListView. And this will cancle the edit.
I'm not yet sure how to mitigate this...

**Comment by Dirkster99** [comment]
I am not sure what your problem is - your minimal sample link is dead but I won't have the time to debug it anyways... please have a look at the linked [Codeproject article](https://www.codeproject.com/Articles/802385/A-WPF-MVVM-In-Place-Edit-TextBox-Control) and its downloads as I am pretty sure there is a sample based on a ListView or even a ListBox - I just don't know all the details anymore as this was done quit a long time ago ...
